"""ChangePlan model defining structured planning output from Change Analyst Agent."""
from enum import Enum
from typing import List
from pydantic import BaseModel, Field


class ChangeType(str, Enum):
    CREATE = "CREATE"
    MODIFY = "MODIFY"
    DELETE = "DELETE"


class ImpactedFile(BaseModel):
    """File identified as relevant or impacted by the change."""
    path: str = Field(..., description="Relative file path within repository")
    reason: str = Field(..., description="Explanation of why this file is impacted")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence score between 0.0 and 1.0")


class PlannedChange(BaseModel):
    """Specific planned file mutation."""
    file_path: str = Field(..., description="Relative file path to mutate")
    change_type: ChangeType = Field(..., description="Operation type: CREATE, MODIFY, or DELETE")
    description: str = Field(..., description="Detailed description of the planned changes to this file")


class ChangePlan(BaseModel):
    """Structured change plan generated by Change Analyst Agent."""
    story_id: str = Field(..., description="Story identifier matching ChangeRequest")
    summary: str = Field(..., min_length=10, description="Executive summary of the proposed changes")
    impacted_files: List[ImpactedFile] = Field(default_factory=list, description="List of all files analyzed/impacted")
    planned_changes: List[PlannedChange] = Field(..., min_length=1, description="Deterministic list of file modifications")
    dependencies: List[str] = Field(default_factory=list, description="External or internal dependencies affected")
    risks: List[str] = Field(default_factory=list, description="Identified technical or regression risks")
    testing_strategy: List[str] = Field(default_factory=list, description="Approach for testing and verifying the changes")
    clarifications: List[str] = Field(default_factory=list, description="Assumptions or clarifying notes")
